name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: How will it help?
      description: It's helpful to include examples (like in your use case).
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Extra info
      description: If you want a new widget, a pic of the inspiration (if available) would be awesome.